name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Bỏ qua cảnh báo Node.js 20
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@master # Dùng bản master để cập nhật fix mới nhất
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-solutions
